name: perturbation-test
on: [push]
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - name: update_data
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          # load data
          python3 ./src/update_data.py

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Update data
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
