name: data
on:
  push:
    branches:
      - 1min
<<<<<<< HEAD
=======
      - main
>>>>>>> 65dfbf43d520a787f7b2d48945ca00515b2220d9
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - name: update_ADA_data
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          
          # install requirements
          pip3 install -r src/data/requirements.txt
          
          # load data 
          python3 src/data/update_ada.py