name: train
on:
  push:
    branches:
      - 1min
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
      - name: Display structure of download files
        run: ls -R
      - name: model inference
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # install requirements
          pip3 install -r src/train/requirements.txt
          
          # inference
          python3 src/inference/inference.py
