name: perturbation-test
on: [push]
jobs:
  run:
    runs-on: [self-hosted,cml,gpu]
    # container: docker://blonc/lightgbm-gpu:latest
    # container: docker://dvcorg/cml-py3:latest 
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: iterative/setup-cml@v1
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Run the test
          # pip install -r requirements.txt
          # pip install dvc[gs]
          # pip install lightgbm --install-option=--cuda
          
          # load data 
          dvc pull data
          # echo ====================================================== 
          python3 baseline.py
          
          echo "## feature importances" >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          echo "## prediction result" >> report.md
          cml-publish result.png --md >> report.md
          cml-send-comment report.md

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
