name: perturbation-test
on:
  push:
    branches:
      - 1min
jobs:
  run:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - uses: iterative/setup-cml@v1
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # load data 
          python3 src/train/train.py
          
          echo "## feature importances" >> report.md
          cml-publish feature_importance.png --md >> report.md
          
          echo "## train result" >> report.md
          cml-publish result.png --md >> report.md
          
          echo '## train scores" >> report.md
          cml-publish score.json --md >> report.md
          
          cml-send-comment report.md

      - name: save model file
        uses: actions/upload-artifact@v3
        with:
          path: trained_model_fold*

      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          author_name: Model Training # default: 8398a7@action-slack
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
